"""Wisdom-mode stub: produces `wisdom/` notes by diffing `knowledge/` across Git.

This is *not* a real LLM-backed synthesiser. It is the minimum code that
closes the DIKW-T loop: for each file in `knowledge/` that has ≥ 2 Git
commits, produce a `wisdom/<stem>.md` summarising the revision chain — when
it was created, how many times it changed, and the commit messages tying
each revision to its trigger (which `notes/` or `inbox/` file drove the
change).

Replace the body of `_synthesise()` with a real Hermes wisdom-mode call when
one ships; the interface — read knowledge + git log, write wisdom — stays
stable.
"""
from __future__ import annotations

import logging
import subprocess
from dataclasses import dataclass
from pathlib import Path

log = logging.getLogger(__name__)


@dataclass
class WisdomResult:
    project: str
    processed: int
    produced: list[str]
    skipped: list[str]


def synthesise_project(vault_dir: Path, project_slug: str) -> WisdomResult:
    """Run wisdom synthesis for one project. Returns a summary of what changed."""
    knowledge_dir = vault_dir / "knowledge"
    wisdom_dir = vault_dir / "wisdom"
    wisdom_dir.mkdir(parents=True, exist_ok=True)

    if not knowledge_dir.is_dir():
        return WisdomResult(project=project_slug, processed=0, produced=[], skipped=[])

    produced: list[str] = []
    skipped: list[str] = []
    processed = 0
    for src in sorted(knowledge_dir.glob("*.md")):
        processed += 1
        rel = src.relative_to(vault_dir).as_posix()
        commits = _git_history(vault_dir, rel)
        if len(commits) < 2:
            skipped.append(rel)
            continue
        out_path = wisdom_dir / src.name
        out_path.write_text(_synthesise(rel, commits))
        produced.append(out_path.relative_to(vault_dir).as_posix())
    return WisdomResult(
        project=project_slug, processed=processed, produced=produced, skipped=skipped
    )


def _git_history(vault_dir: Path, rel_path: str) -> list[dict]:
    """Return [{hash, iso, author, msg}, ...], newest first. Empty if no repo."""
    if not (vault_dir / ".git").exists():
        return []
    try:
        out = subprocess.run(
            [
                "git", "log",
                "--follow",
                "--pretty=format:%H%x1f%cI%x1f%an%x1f%s",
                "--", rel_path,
            ],
            cwd=vault_dir,
            check=True,
            capture_output=True,
            text=True,
        ).stdout
    except subprocess.CalledProcessError as e:
        log.warning("git log failed for %s: %s", rel_path, e)
        return []
    entries = []
    for line in out.splitlines():
        parts = line.split("\x1f")
        if len(parts) != 4:
            continue
        h, iso, author, msg = parts
        entries.append({"hash": h, "iso": iso, "author": author, "msg": msg})
    return entries


def _synthesise(knowledge_path: str, commits: list[dict]) -> str:
    """Render a deterministic Wisdom note from a file's commit history.

    Stub implementation — no LLM. Lists revisions, highlights change cadence,
    and surfaces the source file (inbox/ or notes/) if the commit message
    mentions one. A real Hermes wisdom-mode pass would replace this body.
    """
    first, last = commits[-1], commits[0]
    lines: list[str] = []
    lines.append(f"# Wisdom: {Path(knowledge_path).stem}")
    lines.append("")
    lines.append(
        f"_Why this knowledge changed — derived from {len(commits)} Git revisions "
        f"of `{knowledge_path}` between {first['iso'][:10]} and {last['iso'][:10]}._"
    )
    lines.append("")
    lines.append("## Evolution")
    lines.append("")
    for c in commits:
        source = _trigger_source(c["msg"]) or "—"
        lines.append(
            f"- `{c['hash'][:7]}` · {c['iso'][:19]} · **{c['author']}** · "
            f"triggered by `{source}`"
        )
        lines.append(f"  _{c['msg']}_")
    lines.append("")
    lines.append(
        "> Generated by the DIKW-T wisdom stub. Replace with a real "
        "synthesis pass (Hermes wisdom mode) to get semantic 'why it "
        "changed' analysis rather than a commit list."
    )
    return "\n".join(lines) + "\n"


def _trigger_source(commit_msg: str) -> str | None:
    """Pull the source file out of a commit message if the format includes one."""
    import re
    m = re.search(r"(inbox/[\w./-]+|notes/[\w./-]+)", commit_msg)
    return m.group(1) if m else None
