#!/usr/bin/env bash
# deploy-new-server.sh — full provision on a bare Ubuntu/Debian box.
#
# Run as root on a fresh server. Installs git, clones the repo, generates a
# secure .env, then hands off to `server.sh deploy` (systemd + Caddy + Docker
# CouchDB). Idempotent — safe to re-run.
#
# Usage:
#   sudo ./deploy-new-server.sh                               # uses defaults
#   sudo REPO_URL=... INSTALL_DIR=/opt/ckp DOMAIN=ckp.example.com ./deploy-new-server.sh
#
# Curl-friendly:
#   curl -fsSL https://raw.githubusercontent.com/bejranonda/Cloud-Knowledge-Platform/main/scripts/deploy-new-server.sh \
#     | sudo DOMAIN=ckp.example.com bash
#
# Env knobs:
#   REPO_URL     git URL to clone (default: bejranonda/Cloud-Knowledge-Platform on GitHub)
#   REPO_REF     branch / tag / sha to check out (default: main)
#   INSTALL_DIR  where to clone the repo (default: /opt/ckp)
#   DOMAIN       public hostname for Caddy (optional; edits Caddyfile if set)
#   ADMIN_EMAIL  email for Caddy/ACME (optional)

set -euo pipefail

REPO_URL="${REPO_URL:-https://github.com/bejranonda/Cloud-Knowledge-Platform.git}"
REPO_REF="${REPO_REF:-main}"
INSTALL_DIR="${INSTALL_DIR:-/opt/ckp}"
DOMAIN="${DOMAIN:-}"
ADMIN_EMAIL="${ADMIN_EMAIL:-}"

die()  { echo "ERROR: $*" >&2; exit 1; }
log()  { echo "  $*"; }
step() { echo ""; echo "── $* ──"; }

[ "$(id -u)" -eq 0 ] || die "run as root (sudo $0)"
command -v apt-get >/dev/null 2>&1 || die "this script targets Debian/Ubuntu (apt)"

step "Prereqs (git, curl, openssl)"
export DEBIAN_FRONTEND=noninteractive
apt-get update -qq
apt-get install -y -qq git curl ca-certificates openssl
log "ok"

step "Clone $REPO_URL → $INSTALL_DIR (ref: $REPO_REF)"
if [ -d "$INSTALL_DIR/.git" ]; then
  log "repo already present — fetching latest"
  git -C "$INSTALL_DIR" fetch --quiet origin
  git -C "$INSTALL_DIR" checkout --quiet "$REPO_REF"
  git -C "$INSTALL_DIR" pull --ff-only --quiet origin "$REPO_REF" || true
else
  mkdir -p "$(dirname "$INSTALL_DIR")"
  git clone --quiet --branch "$REPO_REF" "$REPO_URL" "$INSTALL_DIR"
fi
log "ok"

step "Generate .env (if missing)"
ENV_FILE="$INSTALL_DIR/.env"
if [ ! -f "$ENV_FILE" ]; then
  ADMIN_TOKEN="$(openssl rand -hex 32)"
  COUCH_PW="$(openssl rand -base64 18 | tr -d '=+/')"
  cat > "$ENV_FILE" <<EOF
# Generated by deploy-new-server.sh on $(date -u +%FT%TZ)
CKP_ADMIN_TOKEN=$ADMIN_TOKEN
COUCHDB_USER=admin
COUCHDB_PASSWORD=$COUCH_PW
CKP_COUCHDB_URL=http://admin:$COUCH_PW@127.0.0.1:5984
EOF
  chmod 600 "$ENV_FILE"
  log "wrote $ENV_FILE (admin token + CouchDB password generated)"
else
  log "$ENV_FILE already exists — leaving untouched"
fi

if [ -n "$DOMAIN" ]; then
  step "Caddy domain: $DOMAIN"
  CADDY_SRC="$INSTALL_DIR/deploy/caddy/Caddyfile"
  if [ -f "$CADDY_SRC" ]; then
    sed -i -E "s/^[[:space:]]*\{?\\\$?CKP_DOMAIN[^[:space:]]*/$DOMAIN/; s/example\.com/$DOMAIN/g" "$CADDY_SRC" || true
    [ -n "$ADMIN_EMAIL" ] && sed -i -E "s/admin@example\.com/$ADMIN_EMAIL/g" "$CADDY_SRC" || true
    log "patched $CADDY_SRC"
  else
    log "no $CADDY_SRC found — skipping Caddy patch"
  fi
fi

step "Hand off to server.sh deploy"
cd "$INSTALL_DIR"
chmod +x scripts/server.sh
./scripts/server.sh deploy

step "Done"
echo ""
echo "════════════════════════════════════════════════"
echo " Cloud Knowledge Platform deployed"
echo "════════════════════════════════════════════════"
echo " repo       : $INSTALL_DIR"
echo " env        : $ENV_FILE  (chmod 600 — keep secret)"
[ -n "$DOMAIN" ] && echo " domain     : $DOMAIN  (point DNS A record to this box)"
echo ""
echo " admin token: $(grep '^CKP_ADMIN_TOKEN=' "$ENV_FILE" | cut -d= -f2)"
echo ""
echo " Next:"
echo "   - point DNS to this server (if using DOMAIN)"
echo "   - ./scripts/server.sh status"
echo "   - ./scripts/server.sh upgrade   # for future updates"
